import { useState } from "react";
import "./Welcome.scss";
import LogoD from "@/images/logo-d.svg";
import LogoL from "@/images/logo-l.svg";
import { useAppSelector } from "@/store/hooks";
import Checkbox from "./utils/checkbox";

export default function Welcome() {
  const [isActive, setIsActive] = useState<boolean>(
    localStorage.getItem("welcomeDisabled") ? false : true
  );
  const [dialogDisabled, setDialogDisabled] = useState<boolean>(false);
  const lightMode = useAppSelector((state) => state.settings.themeLight);

  return (
    <div className={`Welcome ${isActive && "active"}`}>
      <img
        src={lightMode ? LogoL : LogoD}
        style={{ width: "100%", height: "125px" }}
      />
      <p style={{ fontSize: "14px", margin: "10px 0" }}>
        Welcome to BreezeOS, an operating system (not really) generated by an
        organization using ReactJS and SASS. This will be the revolutionary
        project of bringing the lightweight desktop to your computer.
        <br />
        You're currently using the web browser version of BreezeOS. To get more
        features, install app "BreezeOS Native" to your computer by clicking
        "Install BreezeOS Native".
      </p>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            marginBottom: "15px",
          }}
        >
          <Checkbox
            active={dialogDisabled}
            onToggle={() => setDialogDisabled(!dialogDisabled)}
          />
          <p style={{ fontSize: "12px", marginLeft: "8px" }}>
            Don't show this again
          </p>
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            marginBottom: "15px",
          }}
        >
          <div
            className="Button"
            onClick={() => {
              setIsActive(false);
              if (dialogDisabled) {
                localStorage.setItem("welcomeDisabled", "true");
              }
            }}
          >
            Close
          </div>
          <div
            className="Button install"
            onClick={() => {
              setIsActive(false);
              if (dialogDisabled) {
                localStorage.setItem("welcomeDisabled", "true");
              }
            }}
          >
            Install BreezeOS Native
          </div>
        </div>
      </div>
    </div>
  );
}
